examples/magnus_macro/README.md

Initial magnus readme added, configs to be added soon.

Added initial magnus info

---

examples/joey_sprint/README.md
examples/joey_sprint/configs/repos.yaml
examples/joey_sprint/spack_joey_utils.sh

Provides a script that setups a spack for joey sprint. Copies and updates appropriate configs.

Added a script for starting spack setup

---

examples/joey_sprint/configs/packages.yaml
examples/joey_sprint/spack_joey_utils.sh

the `cray-python` module provides several different packages. I have manually added these entries to the packages yaml file. Initial tests installing `py-scikit-learn` showed no issue.

Update to packages yaml to add python packages 

---

examples/joey_sprint/env_io/spack.yaml

Added spack io environment. Still needs updates for netcdf. Open question as to whether the specific version dependencies in the recipes of netcdf are required.

Added IO environment

---

setonix/environments/env_apps/spack.yaml
setonix/environments/env_apps/wrf.yaml

This pull request separates the wrf spec, so it can be build with "--only dependencies"

Joey sprint update

---

setonix/repo_setonix/packages/ffmpeg/package.py

Spec:
ffmpeg@4.4 +avresample
works out of the box.
Only issues:
- It asks for an interactive question:
Warning: There is no checksum on file to fetch ffmpeg@4.4 safely. ==>   Fetch anyway? [y/N]
- At the end gives a warning about modules:
==> Warning: cannot perform the requested write operation on module files [some tokens cannot be part of the module naming scheme [variants]. Did you check your "modules.yaml" configuration?]

ffmpeg@4.4

---

setonix/configs_spackuser_pawseystaff/config.yaml

Correct typo in systemwise config.

---

examples/joey_sprint/configs/packages.yaml
setonix/environments/env_utils/spack.yaml
setonix/repo_setonix/packages/autoconf/package.py

* Let autoconf perl #! replacement match without '-w' parameter on perl.
* Update gnuplot ver to 5.4.2 (which matches known SHAs).
* Remove errant @ in packages.yaml

autoconf+gnuplot fixes

---

setonix/configs_spackuser_pawseystaff/modules.yaml
setonix/environments/env_s3_clients/spack.yaml

Just added a new environment to provide S3 clients and updated modules produced

Added S3 clients

---

setonix/configs_site_allusers/modules.yaml
setonix/configs_spackuser_pawseystaff/modules.yaml
setonix/templates_setonix/modules/modulefile.lua

Module template updated to alter order of information
Also, removed '.lua' in the module yaml files as this results in '.lua.lua' files

Update to modules

---

setonix/configs_site_allusers/packages.yaml

* Remove gettext from pre-installed list
* Set package version for gnuplot to 5.4.2 instead of 5.4.1 to match spack default recipe.

Fixes for gnuplot.

---

setonix/repo_setonix/packages/kokkos/package.py

Prior to update kokkos used std= to set the cxx standard. All other packages
conform to using cxxstd=

Update the kokkos recipe to use the more standard cxxstd option

---

setonix/configs/spackuser_pawseystaff/modules.yaml
setonix/environments/env_apps/spack.yaml
setonix/environments/env_astro/spack.yaml
setonix/environments/env_num_libs/spack.yaml

Update to deal with python 3.9.9 cropping up and also removed amd libraries for now. Includes update to fix mpi4py module.

Update env yamls

---

setonix/setup_scripts/install_software_stack.sh
setonix/setup_scripts/variables.sh

Updated pip version in variables.sh & removes the spack command that installs singularity in the installer script.

Fix shpc build & other improvements

---

setonix/configs/site_allusers/compilers.yaml

update to yaml. Will require uninstalling all the stuff installed by spack has hash will change now.

Added xpmem to the compiler config

---

systems/setonix/settings.sh

one-liner: updated shpc registry version (commit hash)

setonix/settings: updated shpc registry version

---

systems/setonix/settings.sh

only a change of order in settings.sh for setonix, for consistency

setonix settings: list of container images in right part of file

---

scripts/create_custom_singularity_modules.sh
scripts/create_custom_singularity_modules_from_general_singularity_container_engine.sh

Adds sed command to remove load commands.

---

systems/setonix/settings.sh

2023.08 deployment prep

---

repo/packages/namd/package.py

I have updated a tarball name and checksum for namd 2.15a.

tarball name updated

---

repo/packages/ansys-fluids/package.py
systems/setonix/environments/apps/spack.yaml

We tested the installation on my local software area on Setonix.

updating ansys-fluids recipe

---

systems/setonix/settings.sh

This PR must be merged after the one opened to SHPC Registry:
https://github.com/singularityhub/shpc-registry/pull/177/files

Adds PyTorch and TensorFlow container installation.

---

repo/packages/dftd4/package.py
repo/packages/mctc-lib/package.py
repo/packages/vasp/package.py

to support the research group of Dino Spagnoli.

Adds D4 VASP modification

---

systems/setonix/configs/spackuser/modules.yaml

Will be good to test this update on Joey, make sure there are no module conflicts.

Updates to packages that will have visible libraries

---

repo/packages/singularityce/package.py

Set `shared loop devices` to `yes`

---

systems/setonix/settings.sh

I have worked on an improved container for PyTorch. It is online, waiting for the SHPC recipe to get updated before merging this one.

Bumps version of PyTorch

---

systems/setonix/settings.sh

New version of the PyTorch container that fixes the installation of `torchaudio` and bumps the version of PyTorch from `2.1.2` to `2.2.0`.

Updates PyTorch container.

---

systems/setonix/custom/amber_gpu.sh

This is the recipe I used to install amber gpu on Setonix. Craig tested the installation successfully.

Adds amber gpu recipe.

---

repo/packages/giant-squid/package.py
repo/packages/hyperbeam/package.py
repo/packages/mwalib/package.py
repo/packages/py-maturin/package.py

This was tested on Setonix on Spack 0.19
No module available to test on Spack 0.21

add mwa packages

---

repo/packages/birli/package.py
repo/packages/giant-squid/package.py
repo/packages/hyperbeam/package.py
repo/packages/hyperdrive/package.py
repo/packages/mwalib/package.py
systems/setonix/environments/astro/spack.yaml
systems/setonix/environments/rocm/spack.yaml

Updates some MWA software for the May 2025 Pawsey maintenance:
- Birli to v0.17.1
- giant-squid to v2.1.0
- hyperbeam to v0.10.2
- hyperdrive to v0.5.1
- mwalib to v1.8.7

Updated Birli,giant-squid,hyperdrive,hyperbeam and mwalib

---

systems/setonix/settings.sh

This updates the list of mpi containers and the shpc registry version to facilitate pulling of newer containers

Update shpc registry and mpi container versions
