PawseySC/pawsey-spack-config

setonix/environments/env_apps/spack.yaml, setonix/repo_setonix/packages/gromacs/gmxDetectCpu-cmake-3.14.patch, setonix/repo_setonix/packages/gromacs/gmxDetectSimd-cmake-3.14.patch, setonix/repo_setonix/packages/gromacs/package.py, setonix/repo_setonix/packages/plumed/package.py
Gromacs was the only software that needed a recipe modification in order to work. I have basically told spack it is ok to patch gromacs@2021.4 with plumed 2.7.2 even though that specific version is not listed as supported.
=> Gromacs modified recipe + spec

setonix/configs_site_allusers/packages.yaml, setonix/environments/env_apps/spack.yaml, setonix/repo_setonix/packages/openfoam/1612-spack-patches.patch, setonix/repo_setonix/packages/openfoam/common/README, setonix/repo_setonix/packages/openfoam/common/README-spack, setonix/repo_setonix/packages/openfoam/common/change-sitedir.sh, setonix/repo_setonix/packages/openfoam/common/change-userdir.sh, setonix/repo_setonix/packages/openfoam/common/spack-Allwmake, setonix/repo_setonix/packages/openfoam/common/spack-derived-Allwmake, setonix/repo_setonix/packages/openfoam/common/spack-dummy-Allwmake, setonix/repo_setonix/packages/openfoam/package.py
Failed Spec:
openfoam@v2012 +paraview +vtk
Mainly because of failure to install paraview which is giving troubles with osmesa and qt
Good Spec so far:
openfoam@v2012
Main modifications to make this work:
- New package.py recipe to allow set compilation with cray-gcc and fileHandler collated as default for the installation
- Modification of packages.yaml to allow for spack installation of texinfo
=> openfoam@2012

setonix/configs_site_allusers/packages.yaml, setonix/environments/env_astro/spack.yaml, setonix/environments/env_num_libs/spack.yaml, setonix/environments/env_python/spack.yaml, setonix/environments/env_utils/spack.yaml
cuda=off typo resulted in issues with `spec slate` 
Also reorganised the num_libs which does contain not just numerical libraries but parallelism libraries.
=> Update to yamls including critical fix to packages.yaml

setonix/configs_site_allusers/packages.yaml
Before the edit, packages.yaml had two entries for sqlite and gettext;
YAML parsing is only able to manage one entry for each key (can't recall which one gets to be used, probably the latest in parsing order).
In this PR, I have got rid of the version preferences for sqlite and gettext;
this was not needed any way, because the other entry for these two packages sets them as externals and non buildable, with the desired versions.
=> setonix site config: removed unnecessary version prefs for 2x externals

setonix/configs_site_allusers/packages.yaml
- I have changed default write settings to "user", to avoid Pawsey staff inadvertently editing the system wide installation outside of the "spack" user
- I have changed the group ownership from "pawsey0001" to "$PAWSEY_PROJECT", so that it works for all users
=> setonix packages.yaml: edit to permission settings

setonix/configs_site_allusers/packages.yaml
using default group ownership:
- fine, considering world readable and user writable
- could not use $PAWSEY_PROJECT, as variables are apparently not evaluated here
=> setonix packages: using default group ownership

setonix/configs_site_allusers/config.yaml, setonix/configs_site_allusers/repos.yaml, setonix/configs_spackuser_pawseystaff/config.yaml, setonix/extras/marco-setup-joey.sh
The previous repo setup I did was scanning:
1. a USER specific location for recipes (would be empty for vast majority of users)
2. the setonix location with our Pawsey fixed recipes
In this setup, if a repo is empty, Spack will print a warning at every command, which I reckon can be annoying/distracting.
Considering not many users are likely to need to edit recipes, this PR does two things:
1. removes the USER specific location for recipes (`repos.yaml`)
2. for consistency with 1., also removes the USER specific location for templates (`config.yaml`). There's no warning here. However, considering that also this one is likely to be empty for most users, I though of let consistency prevail.
For powerusers of Spack, we can document how to customise their `~/.spack` yamls to edit these …
=> setonix: repos/templates only from pawsey-config path

setonix/configs_site_allusers/modules.yaml, setonix/configs_spackuser_pawseystaff/modules.yaml
unless specifically set otherwise.
This address the issue of modules not loading dependencies by default which is an issue for all libraries. The use of Rpath means that this is not an issue for applications and hence these applications will by default NOT autoload anything.
=> Update to the autoload of modules. Now default is direct

setonix/fixes/modulenames_plus_common.patch, setonix/fixes/modulenames_plus_init.patch, setonix/setup/setup_spack.sh
@pelahi , I have turned your Spack branch with the extra modulefiles features, into two patches that can be applied to the stable branch.
My rationale is, for features that won't enter Spack's develop soon (eg because they're Pawsey specific), probably better to have them in the form of patches in this repo, as they maybe easier to locate, characterise and maintain over time.
Thoughts?
If it seems fine to you, please go ahead and merge.
=> setonix setup: added patches for Pascal,s enhancements to modulefiles

setonix/repo_setonix/packages/nektar/package.py
Currently it is very difficult to compile nektar when using external
dependencies. However, by altering the recipe to not list dependencies
such as boost, hdf5, blas, nektar will build these libraries internally.
There appears to be no issue with dynamic libraries so nektar should be
fully self-contained.
=> Hacked recipe for nektar

setonix/repo_setonix/packages/amber/aarch64.patch, setonix/repo_setonix/packages/amber/ambertools_configure2.patch, setonix/repo_setonix/packages/amber/ambertools_configure2_cray_shasta.patch, setonix/repo_setonix/packages/amber/ambertools_configure2_for_netcdf.patch, setonix/repo_setonix/packages/amber/cpptraj_configure.patch, setonix/repo_setonix/packages/amber/cpptraj_configure_netcdf.patch, setonix/repo_setonix/packages/amber/nvhpc-boost.patch, setonix/repo_setonix/packages/amber/nvhpc.patch, setonix/repo_setonix/packages/amber/package.py, setonix/repo_setonix/packages/amber/ppc64le.patch
Added patches to the configure scritps to handle cray shasta for gnu and separate netcdf-c and netcdf-fortran installation directories.
The updates to a cray-shasta build are currently for gnu only, built with cray-shasta-gnu as the compiler selection. Furhter updates to this will be required for cray compilers and aocc compilers.
Currently the code can manually build but there is an remaining issue with spack builds. When installing with spack, the resulting make file will try to build a larger selection of amber tools, which do not compile. Manually configuring the code with seeminly the same configure command does not try to make these tools and will successfully build the code. Further digging is required to determine what the issue is.
=> Update to amber recipe

setonix/configs/site_allusers/packages.yaml
1. set openssh to buildable
2. set openssl to buildable
3. took out default +ssl from python
=> setonix: openssl and openssh external set to buildable

setonix/repo/packages/plumed/package.py, setonix/repo/packages/plumed/plumed-2.6.1-include-limits.patch
Add a patch for plumed 2.6.1 that fixes a build failure due to a missing #include.
=> Patch plumed missing include file.

setonix/environments/env_devel/spack.yaml, setonix/environments/env_io_libs/spack.yaml, setonix/environments/env_langs/spack.yaml, setonix/environments/env_num_libs/spack.yaml, setonix/environments/env_python/spack.yaml, setonix/environments/env_s3_clients/spack.yaml, setonix/environments/env_utils/spack.yaml
The fact that the desired python does not contain a hash in the recipe seems to introduce a bug in the concretization. This bug results in a version of python other than what is requested being built. This bug is fixed by explicitly having the python version in the environment.
=> update to spack.yamls to include specific py ver

setonix/environments/env_python/spack.yaml
If we have multiple pythons the creation of the hpc collection view breaks.
Other Python instances will still be compiled in env_langs. This environment is purely needed for the HPC python collection view.
=> Only use python%gcc12 in env_python.

setonix/repo/packages/charmpp/deserpenticate.patch, setonix/repo/packages/charmpp/package.py
* Remove the Python build+link test from the charm++ configure script that is incorrectly determining that Python support in the PythonCCS component can be built in a Python 3-only environment.
Fixes #131
=> Remove Python test triggering charm++ build bug

setonix/setup_scripts/update_user_spack_installs_after_spack_update.sh
If users use spack to install software, after updates the users may have software that needs to be reinstalled as the compilers and older dependencies are no longer present in the currenty spack deployment. This script will find all packages given a compiler@version and uninstall and reinstall as required. Further updates and ammends to the script are likely.
=> Added script to manage user installations of software

joey/environments/env_apps/spack.yaml, joey/repo/packages/openfoam/package.py, setonix/environments/env_apps/spack.yaml, setonix/repo/packages/openfoam/package.py
This new recipe for openfoam@2206 works on Setonix.
This "solves" the issues faced with previous recipe/settings for installing openfoam@2012 which fails to compile properly with gcc@12.
Note: this new recipe/setting still does not catch errors when trying for openfoam@2012. So, if you try to install openfoam@2012, compilation of solvers will fail, but spack will consider the installation as successful. Therefore, some future work is needed to be able to properly handle erroneous compilations.
=> Updating to openfoam@2206 as 2012 is failing with gcc@12

setonix/configs/spackuser_pawseystaff/modules.yaml
Previously, the creation of openfoam module was blocked because pawsey offers several openfoam flavours@versions as containerised modules.
But, in order to count with at least one bare-metal install, now the line that allows openfoam module creation for spack bare-metal install has been made active.
=> Allowing openfoam module to be created

fixes/dot_spack.patch, scripts/install_spack.sh, systems/setonix/configs/site/bootstrap.yaml, systems/setonix/settings.sh
This will avoid hitting the /home quota, and will allow the user to have a different spack cache for each project. But most importantly, it will allow us to parametrise the user configuration path (a.k.a ~/.spack) based on the software stack version.
Opening this merge request for you to review the strategy, do not merge yet, more testing is needed.
=> Moves the `~/.spack` directory to /software

fixes/dot_spack.patch, scripts/install_shpc.sh, scripts/install_spack.sh, scripts/templates/pawseyenv.lua, scripts/templates/spack.lua, scripts/templates/spack_create_user_moduletree.sh, systems/setonix/configs/project/config.yaml, systems/setonix/configs/project/modules.yaml, systems/setonix/configs/site/config.yaml, systems/setonix/configs/site/modules.yaml, systems/setonix/settings.sh
We are going to version user and project-wide installations. The reasons:
1. Spack user cache of different Spack and software stack deployments must be kept separate, otherwise, there is the risk of installing software in the wrong location.
2. By default, we do not want a user's and project's software stack to depend on a mix of Pawsey stack deployments, for instance starting to install with dependencies in 2022.11 and then moving to 2023.02 after the latter is deployed. This will make it easier to get rid of older software stacks and identify affected users.
3. Spack recipes may not be compatible across Spack versions.
And other reasons I am sure are out there waiting to be found.
Not to merge yet, needs to be tested.
=> Adds DATE_TAG to user and project directory hierarchies.

scripts/install_environments.sh, scripts/install_python.sh, systems/setonix/settings.sh
As per the title, implements the build cache system. Unfortunately it seems that `gpg` does not run well on compute nodes, hence `gpg create` needs to run on login node (unless it gets fixed).
=> Implements build cache.

scripts/install_spack.sh, scripts/templates/spack, scripts/templates/spack_project.sh
Instead of having two executables, `spack` and `spack_project.sh`, we should have a single `spack` command with a `project` subcommand to handle project installations. The proposed solution provides a cleaner interface to users.
=> A spack wrapper to provide single command to handle user and project installations

systems/setonix/configs/spackuser/modules.yaml, systems/setonix/environments/apps/spack.yaml
Hi guys, I propose to add two new software packages to our system-wide stack:
- `feh`, to render images on Setonix using X11 forwarding. It provides users an easy way to open `jpeg`, `png`, and other formats.
- `ncl` is a package used by environmental scientists and has been requested on a number of tickets (see #182).
EDIT:
the `~mpi` variant in the spec of `esmf` comes from the following error
```
>> 5268    /usr/bin/ld: cannot find -lmpi++: No such file or directory
>> 5269    collect2: error: ld returned 1 exit status
>> 5270    make[2]: *** [makefile:35: tracelib_preload] Error 1
```
=> Adds `ncl` and `feh` to the Pawsey provided software.

scripts/install_spack.sh
- Do not overwrite the "real" spack with the wrapper if the script is executed twice.
- Fixes trailing whitespace.
=> Fixes install_spack.sh

repo/packages/blaspp/package.py, repo/packages/lapackpp/package.py, repo/packages/slate/package.py, systems/setonix/custom/omniperf.sh
Added installation script for omniperf:
Installation directory is set as 
/software/setonix/2023.08/custom/software/linux-sles15-zen3/gcc-12.2.0/omniperf/1.0.6
Module path is 
/software/setonix/2023.08/custom/modules/zen3/gcc/12.2.0/custom/omniperf/1.0.6.lua
=> adding installation script for omniperf

scripts/patch_shpc_pawsey_modules.sh, systems/setonix/settings.sh
This HASH of the shpc_registry_version was updated in order to catch the latest contributions of Pawsey into the main shpc-registry repo.
Also, the logic for renaming ${tool} directories to ${tool}-container was modified in order to avoid undesired nesting of directory names when the ${tool}-container directory already exists.
=> Updating the HASH of shpc_registry_version

systems/setonix/settings.sh
Those containers do not work. We will need to install our own. Working on publishing them on Quay.io. I will add the required lines here when that happens.
=> Removes AMD PyTorch and TensorFlow containers

repo/packages/vasp/package.py, repo/packages/vasp/vtst-5:6.1.patch, repo/packages/vasp/vtst-6.3:.patch
* Adds resource, patches to support VTST extenstions for VASP for versions 5.4.4, 6.1, 6.3.
Note that the VASP license does not permit us to install modified versions of VASP; the recipe additions are intended to make it simpler for users to install their own modified versions.
=> Add VTST variant for VASP

scripts/install_spack.sh, systems/setonix/templates/modules/modulefile.lua
There are other things that may need the DATE_TAG parameterization. For instance, NEXTFLOW and Singularity homes. What do you think @marcodelapierre ?
=> Adds DATE_TAG in modulefile template.

systems/setonix/configs/site/packages.yaml, systems/setonix/environments/langs/spack.yaml
@ddeeptimahanti  I needed to comment out rust from the environment otherwise it would conflict with `buildable: false`
=> Sets rust not buildable and comments it out of the environment.

README.md, systems/setonix/configs/site/upstreams.yaml
Previously, user-private Spack installations could not use project-wide installations as dependencies because they were not seen. In other words, the project-wide installation directory was not set as upstream.
Fixes #278
=> Allows project-wide installations to be seen by user-private Spack runs.

repo/packages/casacore/package.py
Casacore comes with some data that is used at runtime, especially time and timezone info. This information is often needed, so we need to compile the package with it. Given that this dataset is to be retrieved with FTP, I downloaded it and installed it under `/scratch/references`. Maybe there is a better way of doing this (FTP within spack?).
https://github.com/casacore/casacore?tab=readme-ov-file#obtaining-measures-data
=> Compiles casacore with Measures data.

systems/setonix/configs/spackuser/modules.yaml, systems/setonix/environments/astro/spack.yaml
In previous PRs, recipes for MWA radio astronomy applications were added to our repository.
This PR modifies the deployment process such that these packages are also installed system-wide at every deployment.
For the next maintenance, the packages will be installed "manually" by implementing these same changes locally to the `spack` user. In that sense, we can use this PR to also double check the changes that will be implemented in the next maintenance.
Paging @d3v-null for awareness.
=> Adds MWA packages to the system-wide installation

systems/setonix/environments/astro/spack.yaml
This is a custom variant that builds casacore with the Measures data installed on Setonix.
For more info, see https://github.com/PawseySC/pawsey-spack-config/pull/286
=> Enables the datapath variant of the Casacore package.

systems/setonix/environments/astro/spack.yaml
The reentrant option allows the use of the library in multithreaded environments https://heasarc.gsfc.nasa.gov/fitsio/c/c_user/node15.html 
Also, adds older 3.49 version for compatibility reasons. Seems like version 4.x breaks some MWA software.
Paging @d3v-null for awareness
=> Enables CFITSIO's reentrant option.

scripts/install_shpc.sh, scripts/templates/spack_create_user_moduletree.sh, systems/setonix/configs/site/repos.yaml
This is useful for research groups to have recipes used by all people belonging to a project.
@pelahi @ilkhomab @ddeeptimahanti what do you think?
=> Allowing installation and use of project-wide Spack and SHPC recipes.

scripts/install_shpc.sh, scripts/templates/pawseyenv.lua, scripts/templates/shpc, scripts/templates/spack_create_user_moduletree.sh, systems/setonix/settings.sh
This PR implements project-wide installations of container modules just like the `spack project` command allows Spack installations to be installed at the project level. Analogously, I implement a `shpc` wrapper script to execute SHPC with a custom configuration when the `project` keyword is passed as a first argument to the script.
=> Enables project-wide installations with SHPC

repo/packages/birli/package.py, repo/packages/hyperbeam/package.py, repo/packages/hyperdrive/package.py, repo/packages/mwalib/package.py, repo/packages/wsclean/mpiv3.5.patch, repo/packages/wsclean/package.py
I've tested a pre-release version of this Birli on setonix already, but my spack environment is trashed again so I can't test this particular tag.
by the way, I've ticked "allow edits by maintainers".
A newer hyperbeam is ready too, but it (and the next hyperdrive) will need rust 1.80 https://pawsey.atlassian.net/servicedesk/customer/portal/3/GS-30920
=> update birli, mwalib, wsclean

systems/setonix/configs/spackuser/modules.yaml
Dev Null requested that the GPU version of hyperbeam and hyperdrive to be named without the usual `amd-gfx90a` suffix, and to add a `cpu` suffix to the CPU versions instead.
@d3v-null please confirm these are the changes you wish for these packages, to keep a record of it.
=> Changes naming convention for Dev Null's packages

systems/setonix/settings.sh
Updates the SHPC registry version so to have the newest Pawsey PyTorch container uploaded at https://quay.io/repository/pawsey/pytorch?tab=tags
=> Update SHPC registry and PyTorch

systems/setonix/environments/utils/spack.yaml
I added ffmpeg +libx264 to utils/spack.yaml but how about other currently disabled variants, such as:
~doc
~drawtext
~libaom
~libmp3lame
~libopenjpeg
~libopus
~libsnappy
~libspeex
~libssh
~libvorbis
~libvpx
~libwebp
~libxml2
~libzmq
~lzma
~nonfree
~openssl
~sdl2
=> Adding +libx264 variant to ffmpeg

systems/setonix/configs/site/config.yaml, systems/setonix/configs/spackuser/config.yaml
It is ignored starting from spack 0.23. See #313
=> Removes the concretizer selection.

scripts/_fixPYTHONSTARTUP.lua, scripts/patch_shpc_pawsey_modules.sh
This variable is being cancelled as it causes annoying error messages when running python inside the containers. The explanation is in tickets GS-32800 adnd GS-31936.
I have tested all commands in separate auxiliary modules and files and logic is proven to work (the physical changes to module files and also the working of the module files after the change has been applied).
=> Cancelling PYTHONSTARTUP variable

scripts/templates/pawseyenv.lua
Setting the `PAWSEY_STACK_VERSION` variable helps user scripts to detect which version of the stack they are currently using.
=> Set helper environment variable in pawseyenv.lua

scripts/create_custom_singularity_modules_from_general_singularity_container_engine.sh, scripts/pawsey_fix_initial_bash.lua, scripts/pawsey_init_bash, systems/setonix/templates/modules/modulefile.lua
Lmod messages like
```
/opt/cray/pe/lmod/lmod/init/bash: line 26: /opt/cray/pe/lmod/lmod/libexec/addto: cannot execute: required file not found
```
are being generated when running certain commands inside singularity shells, due to an upcoming change in the `/opt/cray/pe/lmod/lmod/init/bash` script. This forces the BASH_ENV environment variable to point to the current version of the script when loading singularity, which doesn't trigger these messages, rather than the new version. A ticket for this issue is at GS-32798.
I have tested this setup using separate files from the current installation, and the setting of the env var to point to the different script and subsequent elimination of the lmod messages is working.
=> Remove lmod messages in singularity shells
